var colors = {
    black: '#000000',
    transparent: 'transparent',
    current: 'currentColor',
    charcoal: '#121212',
    white: '#ffffff',
    grey: '#EFEFEF',
    gold: '#F1CC0E',
    darkGold: '#baa27f',
    darkGrey: '#737373',
    lightGrey: '#ebebeb',
    red: '#ff0000',
    ligghtRed: '#fca5a5',
    lightGreyHover: '#A0A0A0',
    darkGreyHover: '#E1E1E1',
    goldHover: '#E9C406',
    blackHover: '#323232',
};
module.exports = {
    content: [
        './site/templates/*.php',
        './site/snippets/**/*.php',
        './site/snippets/blocks//*.php',
        './app/controllers/*.js',
    ],
    theme: {
        fontFamily: {
            brown_regular: ['"BrownStdRegular"', 'serif'],
            brown_bold: ['"BrownStdBold"', 'serif'],
            brown_light: ['"BrownStdLight"', 'serif'],
            brown_thin: ['"BrownStdThin"', 'serif'],
        },
        keyframes: {
            flipInY: {
                from: {
                    transform: 'perspective(400px) rotate3d(0, 1, 0, 90deg)',
                    opacity: 0,
                },
                '40%': {
                    transform: 'perspective(400px) rotate3d(0, 1, 0, -20deg)',
                },
                '60%': {
                    transform:
                        ' transform: perspective(400px) rotate3d(0, 1, 0, 10deg)',
                    opacity: 1,
                },
                '80%': {
                    transform:
                        'transform: perspective(400px) rotate3d(0, 1, 0, -5deg)',
                },
                to: { transform: 'transform: perspective(400px)' },
            },
            fadeIn: {
                from: { opacity: 0 },
                to: { opacity: 1 },
            },
            fadeInUp: {
                from: { opacity: 0, transform: 'translate3d(0, 100%, 0)' },
                to: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
            },
            fadeInLeft: {
                from: { opacity: 0, transform: 'translate3d(-100%, 0, 0)' },
                to: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
            },
            spin: {
                from: { transform: 'rotate(0deg)' },
                to: { transform: 'rotate(360deg)' },
            },
        },
        animation: {
            fadeInLeft: 'fadeInLeft 300ms ease',
            fadeIn: 'fadeIn 300ms ease',
            fadeInUp: 'fadeInUp 800ms ease',
            flipInY: 'flipInY 300ms ease-in',
            spin: 'spin 1s linear infinite',
        },
        screens: {
            sm: { raw: '(min-width: 768px)' },
            md: { raw: '(min-width: 1024px)' },
            lg: { raw: '(min-width: 1250px)' },
            xl: { raw: '(min-width: 1921px)' },
            portrait: { raw: '(orientation: portrait)' },
            landscape: { raw: '(orientation: landscape)' },
            widescreen: { raw: '(min-aspect-ratio: 2/1)' },
        },
        container: {
            screens: {
                sm: '100vw',
                md: '100vw',
                lg: '1250px',
            },
        },
        aspectRatio: {
            1: '1',
            2: '2',
            3: '3',
            4: '4',
            5: '5',
            6: '6',
            7: '7',
            8: '8',
            9: '9',
            10: '10',
            11: '11',
            12: '12',
            13: '13',
            14: '14',
            15: '15',
            16: '16',
        },
        colors: { ...colors },
        variants: {
            aspectRatio: ['responsive'],
        },
    },
    corePlugins: {
        aspectRatio: false,
    },
    safelist: [
        'text-sm',
        'text-xs',
        'text-lg',
        'text-xl',
        'text-2xl',
        'text-3xl',
        'bg-black',
        'bg-grey',
        'bg-gold',
        'bg-white',
        'bg-charcoal',
        'pl-0',
        'pl-4',
        'pl-8',
        'pl-12',
        'pl-16',
        'pl-20',
        'pl-24',
        'pr-0',
        'pr-4',
        'pr-8',
        'pr-12',
        'pr-16',
        'pr-20',
        'pr-24',
        'pt-0',
        'pt-4',
        'pt-8',
        'pt-12',
        'pt-16',
        'pt-20',
        'pt-24',
        'pb-0',
        'pb-4',
        'pb-8',
        'pb-12',
        'pb-16',
        'pb-20',
        'pb-24',
        'ml-0',
        'ml-4',
        'ml-8',
        'ml-16',
        'ml-20',
        'ml-24',
        'mr-0',
        'mr-4',
        'mr-8',
        'mr-16',
        'mr-20',
        'mr-24',
        'mt-0',
        'mt-4',
        'mt-8',
        'mt-16',
        'mt-20',
        'mt-24',
        'mb-0',
        'mb-4',
        'mb-8',
        'mb-16',
        'mb-20',
        'mb-24',
        'pt-32',
        'pb-32',
        'opacity-10',
        'opacity-20',
        'opacity-30',
        'opacity-40',
        'opacity-50',
        'opacity-60',
        'opacity-70',
        'opacity-80',
        'opacity-90',
        'opacity-100',
        'md:pb-40',
        'md:pb-48',
        'md:pb-52',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'md:grid-cols-1',
        'md:grid-cols-2',
        'md:grid-cols-3',
        'md:grid-cols-4',
    ],
    plugins: [
        require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
};
