title: Page
icon: page
options:
    preview: '{{ page._preview_url }}'
status:
    draft:
        label: Draft
    unlisted:
        label: Published
tabs:
    content:
        extends: tabs/page-content
        label: On Season
    off: tabs/page-content-off
    access: tabs/page-access
    media: tabs/page-media
    settings:
        extends: tabs/page-settings
