title: Products
status:
    draft:
        label: Draft
    unlisted:
        label: Published
options:
    duplicate: false
    changeTitle: false
    changeStatus: false
    changeTemplate: false
    changeSlug: false
    preview: false
    delete: false
    move: false
tabs:
    items:
        label: Products
        icon: list-numbers
        sections:
            items: sections/products
