type: fields
fields:
    headline_general:
        type: headline
        numbered: false
        label: General
    season:
        type: select
        label: Active Season
        options:
            off: Off Season
            on: On Season
        required: true
    headline_meta:
        type: headline
        numbered: false
        label: Meta Information
    site_title_prefix:
        type: text
        label: Site Title Prefix
    site_description:
        type: textarea
        label: Site Description
        buttons: false
    headline_images:
        type: headline
        numbered: false
        label: Images
    site_logo:
        extends: fields/image
        label: Site Logo (Small)
        width: 1/3
    site_logo_large:
        extends: fields/image
        label: Site Logo (Large)
        width: 1/3
    social_share_image:
        extends: fields/image
        label: Social Share Image
        width: 1/3
    background_1:
        extends: fields/image
        label: Background 1
        width: 1/4
    background_2:
        extends: fields/image
        label: Background 2
        width: 1/4
    background_3:
        extends: fields/image
        label: Background 3
        width: 1/4
    background_4:
        extends: fields/image
        label: Background 4
        width: 1/4

